from pathlib import Path
import re,sys
p=Path(sys.argv[1] if len(sys.argv)>1 else 'neuroatlas/index.html')
s=p.read_text()
if 'SELECTED STRUCTURE ·' in s:
 print('already patched'); raise SystemExit
s=s.replace('.loc{padding:9px 11px;border-top:1px solid var(--line);font:11px/1.45 ui-monospace,Menlo,monospace;color:var(--muted);min-height:38px}', '.selected{padding:10px 11px;border-top:1px solid var(--line);font-size:12px;font-weight:800;color:var(--muted);background:#080d13}.selected span{color:var(--txt);font-size:14px}.loc{padding:9px 11px;border-top:1px solid var(--line);font:11px/1.45 ui-monospace,Menlo,monospace;color:var(--muted);min-height:38px}',1)
s=s.replace('<div class="viewer"><canvas id="gl"></canvas><div class="load" id="loading">Loading real MRI volume and registered atlas…</div></div>\n<div class="ctl">','<div class="viewer"><canvas id="gl"></canvas><div class="load" id="loading">Loading real MRI volume and registered atlas…</div></div>\n<div class="selected" id="selected">SELECTED STRUCTURE · <span>Explore the brain</span></div>\n<div class="ctl">',1)
s=s.replace("const $=s=>document.querySelector(s),loading=$('#loading'),loc=$('#loc'),name=$('#name'),meta=$('#meta'),teach=$('#teach'),op=$('#op'),opv=$('#opv'),q=$('#q');", "const $=s=>document.querySelector(s),loading=$('#loading'),loc=$('#loc'),name=$('#name'),meta=$('#meta'),teach=$('#teach'),op=$('#op'),opv=$('#opv'),q=$('#q'),selected=$('#selected');",1)
pat=re.compile(r"function pretty\(n\)\{return String\(n\|\|''\).*?\.trim\(\)\}")
rep=r'''function pretty(n){let x=String(n||'').trim(),side='';if(/_L$|\bL$/i.test(x)){side='left';x=x.replace(/_L$|\bL$/i,'')}else if(/_R$|\bR$/i.test(x)){side='right';x=x.replace(/_R$|\bR$/i,'')}const m={'Cerebelum_Crus1':'Cerebellar Crus I','Cerebelum_Crus2':'Cerebellar Crus II','Cerebelum_3':'Cerebellar lobule III','Cerebelum_4_5':'Cerebellar lobules IV–V','Cerebelum_6':'Cerebellar lobule VI','Cerebelum_7b':'Cerebellar lobule VIIb','Cerebelum_8':'Cerebellar lobule VIII','Cerebelum_9':'Cerebellar lobule IX','Cerebelum_10':'Cerebellar lobule X','Vermis_1_2':'Cerebellar vermis, lobules I–II','Vermis_3':'Cerebellar vermis, lobule III','Vermis_4_5':'Cerebellar vermis, lobules IV–V','Vermis_6':'Cerebellar vermis, lobule VI','Vermis_7':'Cerebellar vermis, lobule VII','Vermis_8':'Cerebellar vermis, lobule VIII','Vermis_9':'Cerebellar vermis, lobule IX','Vermis_10':'Cerebellar vermis, lobule X','Pallidum':'Globus pallidus','Caudate':'Caudate nucleus','ParaHippocampal':'Parahippocampal gyrus','SupraMarginal':'Supramarginal gyrus','Precentral':'Precentral gyrus','Postcentral':'Postcentral gyrus','Insula':'Insular cortex'};let y=m[x]||x.replace(/_/g,' ').replace(/\bSup\b/g,'Superior').replace(/\bInf\b/g,'Inferior').replace(/\bMid\b/g,'Middle').replace(/\bAnt\b/g,'Anterior').replace(/\bPost\b/g,'Posterior').replace(/\s+/g,' ').trim();return side?`${y} — ${side}`:y}'''
s,n=pat.subn(rep,s,1); assert n==1
old="const JHU_URL='https://raw.githubusercontent.com/MASILab/PreQual/master/src/SUPPLEMENTAL/JHU-ICBM-labels-1mm.nii.gz';\nlet labels=[],jhuReady=false,jhuIndex=-1;"
new="""const JHU_URL='https://raw.githubusercontent.com/MASILab/PreQual/master/src/SUPPLEMENTAL/JHU-ICBM-labels-1mm.nii.gz';
const HO_URL='https://git.fmrib.ox.ac.uk/fsl/data_atlases/-/raw/2103.0/HarvardOxford/HarvardOxford-sub-maxprob-thr25-2mm.nii.gz';
const HO_LABELS=['Background','Left cerebral white matter','Left cerebral cortex','Left lateral ventricle','Left thalamus','Left caudate nucleus','Left putamen','Left globus pallidus','Brainstem','Left hippocampus','Left amygdala','Left nucleus accumbens','Right cerebral white matter','Right cerebral cortex','Right lateral ventricle','Right thalamus','Right caudate nucleus','Right putamen','Right globus pallidus','Right hippocampus','Right amygdala','Right nucleus accumbens'];
const GROUPS={'internal capsule':[17,18,19,20,21,22],'left internal capsule':[18,20,22],'right internal capsule':[17,19,21],'corpus callosum':[3,4,5],'corona radiata':[23,24,25,26,27,28],'external capsule':[33,34],'corticospinal tract':[7,8],'medial lemniscus':[9,10],'cerebral peduncle':[15,16],'cerebellar peduncle':[1,11,12,13,14]};
let labels=[],aalMap=null,jhuReady=false,jhuIndex=-1,hoReady=false,hoIndex=-1,currentSource='',currentIds=[];"""
assert old in s;s=s.replace(old,new,1)
anchor="function sideWord(n){return /(?:\\bR$|right)/i.test(n)?'right':/(?:\\bL$|left)/i.test(n)?'left':''}"
helpers=r'''function mapOnly(ls,ids,key,base=null){const n=ls.length,R=Array(n).fill(0),G=Array(n).fill(0),B=Array(n).fill(0),A=Array(n).fill(0),I=[...Array(n).keys()];let h=0;for(const c of key)h=(h*31+c.charCodeAt(0))>>>0;const rgb=[80+(h%150),90+((h>>8)%140),100+((h>>16)%130)];for(const i of ids){if(i<=0||i>=n)continue;R[i]=base?.R?.[i]??rgb[0];G[i]=base?.G?.[i]??rgb[1];B[i]=base?.B?.[i]??rgb[2];A[i]=240}return{R,G,B,A,I,labels:ls}}function vIdx(src){return src==='AAL'?1:src==='JHU'?jhuIndex:src==='HO'?hoIndex:-1}function setSel(t){selected.innerHTML='SELECTED STRUCTURE · <span>'+esc(t)+'</span>'}function selectStructure(src,ids,label){ids=(Array.isArray(ids)?ids:[ids]).filter(i=>i>0);if(!ids.length)return;setSel(label);const key=src+ids.join(',');if(key===currentSource+currentIds.join(','))return;currentSource=src;currentIds=ids;for(const x of ['AAL','JHU','HO']){const i=vIdx(x);if(i>0&&x!==src&&nv.volumes?.[i])nv.setOpacity(i,0)}nv.opts.atlasActiveIndex=0;const i=vIdx(src),v=nv.volumes?.[i];if(!v)return;if(v.hdr)v.hdr.intent_code=1002;v.setColormapLabel(src==='AAL'?mapOnly(labels,ids,label,aalMap):src==='JHU'?mapOnly(JHU_LABELS,ids,label):mapOnly(HO_LABELS,ids,label));nv.setOpacity(i,+op.value/100);nv.updateGLVolume()}'''
assert anchor in s;s=s.replace(anchor,anchor+helpers,1)
s=s.replace("meta.textContent=source==='JHU'?'White-matter label · JHU ICBM-DTI-81':(Number.isFinite(i)?`Regional atlas label ${i} · AAL`:'MRI location');", "setSel(display);meta.textContent=source==='JHU'?'White-matter label · JHU ICBM-DTI-81':source==='HO'?'Subcortical / ventricular label · Harvard–Oxford':(Number.isFinite(i)?`Regional atlas label ${i} · AAL`:'MRI location');",1)
s=s.replace("function detailFor(n,source='AAL'){if(source==='JHU')return wmDetail(n);", "function detailFor(n,source='AAL'){if(source==='JHU')return wmDetail(n);if(source==='HO'&&/ventricle/i.test(n))return{s:'Ventricular system · CSF space',p:'Axial and coronal',r:n+' is a cerebrospinal-fluid cavity of the lateral ventricular system.',n:['Related to caudate, corpus callosum and thalamus depending on level','Temporal horn lies adjacent to hippocampal structures'],f:'Contains and conveys CSF through the ventricular system.',c:'Ventricular size, symmetry, compression and hydrocephalus are core imaging observations.',t:'Follow the cavity across consecutive axial and coronal slices.'};if(source==='HO')return genericDetail(n);",1)
pat=re.compile(r"function active\(i\)\{.*?\}\nfunction moved\(d\)\{.*?\}\nconst nv=",re.S)
rep=r'''function active(i){if(!Number.isFinite(i)||i<=0)return;const x=labels[i]||`Atlas region ${i}`;selectStructure('AAL',[i],pretty(x));teacher(x,i,'AAL')}function moved(d){const v=d?.values||[],pos=d?.string?`Crosshair: ${d.string}`:'Crosshair moved';let j=0,h=0,a=0;if(jhuReady&&Number.isFinite(v[jhuIndex]?.value))j=Math.round(v[jhuIndex].value);if(hoReady&&Number.isFinite(v[hoIndex]?.value))h=Math.round(v[hoIndex].value);if(Number.isFinite(v[1]?.value))a=Math.round(v[1].value);if(j>0&&JHU_LABELS[j]){const nm=pretty(JHU_LABELS[j]);selectStructure('JHU',[j],nm);teacher(JHU_LABELS[j],j,'JHU');loc.textContent=pos+' · White matter: '+nm;return}if(h>0&&HO_LABELS[h]&&/ventricle|brainstem/i.test(HO_LABELS[h])){selectStructure('HO',[h],HO_LABELS[h]);teacher(HO_LABELS[h],h,'HO');loc.textContent=pos+' · '+HO_LABELS[h];return}if(a>0&&labels[a]){active(a);loc.textContent=pos+' · Region: '+pretty(labels[a]);return}if(h>0&&HO_LABELS[h]){selectStructure('HO',[h],HO_LABELS[h]);teacher(HO_LABELS[h],h,'HO');loc.textContent=pos+' · '+HO_LABELS[h];return}setSel('MRI anatomy — no validated atlas boundary at this exact voxel');loc.textContent=pos+' · No validated named atlas label at this exact voxel'}const nv='''
s,n=pat.subn(rep,s,1); assert n==1
s=s.replace("function refreshSearch(){const all=[...labels.filter(Boolean),...(jhuReady?JHU_LABELS.slice(1):[])];", "function refreshSearch(){const all=[...labels.filter(Boolean).map(pretty),...(jhuReady?JHU_LABELS.slice(1).map(pretty):[]),...(hoReady?HO_LABELS.slice(1):[]),...Object.keys(GROUPS)];",1)
s=s.replace("all.map(x=>`<option value=\"${esc(pretty(x))}\"></option>`)", "[...new Set(all)].map(x=>`<option value=\"${esc(x)}\"></option>`)",1)
pat=re.compile(r"async function loadWhiteMatterAtlas\(\)\{.*?\}\nasync function boot\(\)\{",re.S)
rep=r'''async function loadWhiteMatterAtlas(){try{const v=await nv.addVolumeFromUrl({url:JHU_URL,opacity:0});jhuIndex=nv.volumes.indexOf(v);jhuReady=jhuIndex>=0;if(jhuReady){if(v.hdr)v.hdr.intent_code=1002;v.setColormapLabel(mapOnly(JHU_LABELS,[],''))}}catch(e){console.warn('Optional JHU atlas unavailable',e)}try{const v=await nv.addVolumeFromUrl({url:HO_URL,opacity:0});hoIndex=nv.volumes.indexOf(v);hoReady=hoIndex>=0;if(hoReady){if(v.hdr)v.hdr.intent_code=1002;v.setColormapLabel(mapOnly(HO_LABELS,[],''))}}catch(e){console.warn('Optional ventricular atlas unavailable',e)}refreshSearch();nv.updateGLVolume()}async function boot(){'''
s,n=pat.subn(rep,s,1); assert n==1
s=s.replace("let map=await fetch('https://niivue.com/demos/images/aal.json').then(r=>r.json());labels=Array.isArray(map.labels)?map.labels:[];", "let map=await fetch('https://niivue.com/demos/images/aal.json').then(r=>r.json());aalMap=map;labels=Array.isArray(map.labels)?map.labels:[];",1)
s=s.replace("op.oninput=()=>{opv.textContent=op.value+'%';if(nv.volumes?.[1])nv.setOpacity(1,+op.value/100)};", "op.oninput=()=>{opv.textContent=op.value+'%';const i=vIdx(currentSource||'AAL');if(i>0&&nv.volumes?.[i])nv.setOpacity(i,+op.value/100)};",1)
pat=re.compile(r"function find\(\)\{.*?\}\$\('#find'\)\.onclick=find;",re.S)
rep=r'''function find(){let z=q.value.trim().toLowerCase();if(!z)return;let g=Object.keys(GROUPS).find(k=>z===k||k.includes(z));if(g&&jhuReady){selectStructure('JHU',GROUPS[g],g.replace(/\b\w/g,c=>c.toUpperCase()));teacher(g,GROUPS[g][0],'JHU');loc.textContent='Highlighted structure: '+g+'. Only the requested structure is displayed.';return}let i=labels.findIndex(x=>pretty(x).toLowerCase()===z);if(i<0)i=labels.findIndex(x=>pretty(x).toLowerCase().includes(z));if(i>=0){active(i);loc.textContent='Highlighted regional atlas structure: '+pretty(labels[i])+'. Only the selected region is displayed.';return}if(jhuReady){let j=JHU_LABELS.findIndex(x=>pretty(x).toLowerCase()===z);if(j<0)j=JHU_LABELS.findIndex(x=>pretty(x).toLowerCase().includes(z));if(j>0){const nm=pretty(JHU_LABELS[j]);selectStructure('JHU',[j],nm);teacher(JHU_LABELS[j],j,'JHU');loc.textContent='Highlighted white-matter structure: '+nm;return}}if(hoReady){let h=HO_LABELS.findIndex(x=>x.toLowerCase()===z);if(h<0)h=HO_LABELS.findIndex(x=>x.toLowerCase().includes(z));if(h>0){selectStructure('HO',[h],HO_LABELS[h]);teacher(HO_LABELS[h],h,'HO');loc.textContent='Highlighted structure: '+HO_LABELS[h];return}}meta.textContent='No validated atlas match. Try a broader anatomical name.'}$('#find').onclick=find;'''
s,n=pat.subn(rep,s,1); assert n==1
p.write_text(s)
print('precision patch applied')
