from pathlib import Path
import re, sys

path = Path(sys.argv[1])
s = path.read_text()

# Precision v6: replace the rejected marker/legend cross-section teacher with
# a textbook-style teaching plate. The main NeuroAtlas viewer is untouched.

# Replace the v5 cross-section panel markup. Keep the existing CTA/button.
old_panel = '<div class="cross-panel" id="crossPanel" hidden><div class="cross-head"><div><div class="ey">LABELED CROSS SECTION</div><h3 id="crossTitle">Current slice</h3><div class="tiny" id="crossMeta"></div></div><button id="closeCross">CLOSE</button></div><div class="cross-stage" id="crossStage"><canvas id="crossCanvas"></canvas><div id="crossPins" class="cross-pins"></div></div><div class="cross-legend"><div class="cross-key"><span class="k csf"></span>CSF / ventricular <span class="k wm"></span>white matter <span class="k deep"></span>deep gray <span class="k cortex"></span>cortex / cerebellum</div><div id="crossList" class="cross-list"></div></div></div>'
new_panel = '<div class="cross-panel" id="crossPanel" hidden><div class="cross-head"><div><div class="ey">TEXTBOOK CROSS SECTION</div><h3 id="crossTitle">Current slice</h3><div class="tiny" id="crossMeta"></div></div><button id="closeCross">CLOSE</button></div><div class="cross-stage textbook" id="crossStage"><canvas id="crossCanvas"></canvas></div><div class="cross-note">Leader lines point to atlas-supported structures sampled from this exact MRI slice. Labels are placed outside the anatomy whenever possible.</div></div>'
if old_panel not in s:
    raise SystemExit('v5 cross panel anchor not found')
s = s.replace(old_panel, new_panel, 1)

# Replace the v5 cross-section styling only. Branding and all viewer styling stay intact.
css_pat = re.compile(r'\.cross-cta\{.*?\.foot\{text-align:center', re.S)
m = css_pat.search(s)
if not m:
    raise SystemExit('v5 cross css block not found')
new_css = '''.cross-cta{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 11px;border-top:1px solid var(--line);background:#080d13}.cross-cta>div{display:flex;flex-direction:column;gap:3px}.cross-cta b{font-size:10px;letter-spacing:.14em;color:#d8e8f5}.cross-cta span{font-size:11px;color:var(--muted);line-height:1.35}.cross-cta button:disabled{opacity:.45}.cross-panel{border-top:1px solid var(--line);padding:10px;background:linear-gradient(180deg,#09111a,#070b10)}.cross-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:8px}.cross-head h3{margin:3px 0 2px;font-size:17px}.cross-stage.textbook{background:#020407;border:1px solid #26384b;border-radius:12px;overflow:hidden}.cross-stage.textbook canvas{display:block;width:100%;height:auto;background:#020407}.cross-note{padding:8px 2px 2px;color:var(--muted);font-size:10px;line-height:1.4}.foot{text-align:center'''
s = s[:m.start()] + new_css + s[m.end():]

# Remove obsolete mobile rules for v5 markers/list while keeping current mobile CTA behavior.
s = s.replace('.cross-list{grid-template-columns:1fr}.cross-pin .pin-name{display:none}.cross-pin{padding:3px;max-width:none}', '')

# Replace all v5 cross-section runtime functions with the textbook plate renderer.
pat = re.compile(r'function crossKind\(.*?\nconst nv=new Niivue', re.S)
m = pat.search(s)
if not m:
    raise SystemExit('v5 cross runtime block not found')

cross_js = r'''function crossKind(name,src){const x=String(name||'').toLowerCase();if(/ventricle|aqueduct|csf/.test(x))return{kind:'csf',p:150,color:'#67d8ff'};if(src==='JHU'||/internal capsule|external capsule|corona radiata|corpus callosum|corticospinal|cerebellar peduncle|cerebral peduncle|medial lemniscus|cingulum|fornix|fasciculus|thalamic radiation|sagittal stratum|tapetum/.test(x))return{kind:'wm',p:135,color:'#f3c66d'};if(/thalam|caudate|putamen|pallid|hippocamp|amygdala|accumbens|brainstem|midbrain|pons|medulla/.test(x))return{kind:'deep',p:125,color:'#f48bbb'};if(/cerebel|vermis/.test(x))return{kind:'cortex',p:95,color:'#8fe1ad'};return{kind:'cortex',p:70,color:'#8fe1ad'}}
function crossValue(src,frac){const i=vIdx(src),v=nv.volumes?.[i];if(!v||!v.mm2vox||!v.getValue)return 0;const mm=nv.frac2mm(frac),q=v.mm2vox(mm);return Math.round(v.getValue(q[0],q[1],q[2]))||0}
function crossCanonical(name){let x=String(name||'').toLowerCase().replace(/_/g,' ').replace(/\s+/g,' ').trim(),side='';if(/^left\b/.test(x)){side='l';x=x.replace(/^left\s+/,'')}else if(/^right\b/.test(x)){side='r';x=x.replace(/^right\s+/,'')}else if(/, left$/.test(x)){side='l';x=x.replace(/, left$/,'')}else if(/, right$/.test(x)){side='r';x=x.replace(/, right$/,'')}x=x.replace(/\bnucleus\b/g,'').replace(/\bcortex\b/g,'').replace(/\s+/g,' ').trim();return x+'|'+side}
function crossShortName(name){let x=pretty(String(name||'')).replace(/\s+/g,' ').trim(),side='';if(/^Left\b/i.test(x)){side='L';x=x.replace(/^Left\s+/i,'')}else if(/^Right\b/i.test(x)){side='R';x=x.replace(/^Right\s+/i,'')}else if(/, left$/i.test(x)){side='L';x=x.replace(/, left$/i,'')}else if(/, right$/i.test(x)){side='R';x=x.replace(/, right$/i,'')}else if(/\sL$/i.test(x)){side='L';x=x.replace(/\sL$/i,'')}else if(/\sR$/i.test(x)){side='R';x=x.replace(/\sR$/i,'')}return x+(side?' ('+side+')':'')}
function addCrossBucket(buckets,src,id,name,x,y){if(!id||!name)return;const info=crossKind(name,src),key=crossCanonical(name),rank=(src==='HO'?3:src==='JHU'?2:1);let b=buckets.get(key);if(!b||info.p>b.info.p||(info.p===b.info.p&&rank>b.rank)){b={src,id,name:crossShortName(name),info,rank,pts:[]};buckets.set(key,b)}if(b.src===src&&b.id===id&&b.pts.length<320)b.pts.push([x,y])}
function collectCrossCandidates(){const gl=nv.gl?.canvas||$('#gl'),w=gl.width,h=gl.height;if(!w||!h)return[];const buckets=new Map(),step=Math.max(14,Math.round(Math.min(w,h)/46));for(let y=Math.floor(step/2);y<h;y+=step){for(let x=Math.floor(step/2);x<w;x+=step){const f=nv.canvasPos2frac([x,y]);if(!f||f[0]<0)continue;if(hoReady){const id=crossValue('HO',f),nm=HO_LABELS[id];if(id>0&&nm)addCrossBucket(buckets,'HO',id,nm,x,y)}if(jhuReady){const id=crossValue('JHU',f),nm=JHU_LABELS[id];if(id>0&&nm)addCrossBucket(buckets,'JHU',id,pretty(nm),x,y)}const a=crossValue('AAL',f),an=labels[a];if(a>0&&an)addCrossBucket(buckets,'AAL',a,pretty(an),x,y)}}const arr=[];for(const b of buckets.values()){if(!b.pts.length)continue;let sx=0,sy=0;for(const p of b.pts){sx+=p[0];sy+=p[1]}const mx=sx/b.pts.length,my=sy/b.pts.length;let best=b.pts[0],bd=1e18;for(const p of b.pts){const d=(p[0]-mx)*(p[0]-mx)+(p[1]-my)*(p[1]-my);if(d<bd){bd=d;best=p}}const count=b.pts.length;arr.push({...b,x:best[0],y:best[1],count,score:b.info.p*10000+Math.min(count,999)})}arr.sort((a,b)=>b.score-a.score);const limit=window.innerWidth<=520?18:24;return arr.slice(0,limit)}
function wrapCrossText(ctx,text,maxWidth){const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxWidth||!line)line=test;else{lines.push(line);line=word}}if(line)lines.push(line);return lines.slice(0,2)}
function distributeCrossLabels(items,minY,maxY,gap){items.sort((a,b)=>a.ty-b.ty);let cursor=minY;for(const it of items){it.ly=Math.max(it.ty-it.h/2,cursor);cursor=it.ly+it.h+gap}if(items.length){let overflow=(items[items.length-1].ly+items[items.length-1].h)-maxY;if(overflow>0){for(let i=items.length-1;i>=0;i--){items[i].ly-=overflow;if(i>0){const allowed=items[i].ly-gap-items[i-1].h;if(items[i-1].ly>allowed)overflow=items[i-1].ly-allowed;else overflow=0}}}if(items[0].ly<minY){const d=minY-items[0].ly;for(const it of items)it.ly+=d}}}
function loadCrossImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url})}
function renderTextbookPlate(img,candidates){const dst=$('#crossCanvas'),src=nv.gl?.canvas||$('#gl'),mobile=window.innerWidth<=520,outW=mobile?1080:1500,imgW=mobile?640:900,scale=imgW/src.width,imgH=Math.round(src.height*scale),top=58,bottom=58,outH=Math.max(mobile?860:980,imgH+top+bottom),imgX=Math.round((outW-imgW)/2),imgY=Math.round((outH-imgH)/2),ctx=dst.getContext('2d');dst.width=outW;dst.height=outH;ctx.fillStyle='#020407';ctx.fillRect(0,0,outW,outH);ctx.drawImage(img,imgX,imgY,imgW,imgH);ctx.save();ctx.strokeStyle='rgba(135,157,180,.36)';ctx.lineWidth=1;ctx.strokeRect(imgX+.5,imgY+.5,imgW-1,imgH-1);ctx.restore();const font=mobile?21:23,lineH=font+6,maxText=Math.max(150,imgX-72);ctx.font='600 '+font+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';const placed=candidates.map(c=>{const tx=imgX+c.x/src.width*imgW,ty=imgY+c.y/src.height*imgH,lines=wrapCrossText(ctx,c.name,maxText),h=lines.length*lineH+4;return{...c,tx,ty,lines,h}});const left=[],right=[];for(const p of placed){if(Math.abs(p.tx-(imgX+imgW/2))<imgW*.08){(left.length<=right.length?left:right).push(p)}else(p.tx<imgX+imgW/2?left:right).push(p)}const y0=26,y1=outH-26,gap=mobile?9:10;distributeCrossLabels(left,y0,y1,gap);distributeCrossLabels(right,y0,y1,gap);function drawSide(items,side){for(const it of items){const cy=it.ly+it.h/2,color=it.info.color,textX=side==='left'?imgX-34:imgX+imgW+34,elbowX=side==='left'?imgX-12:imgX+imgW+12,startX=side==='left'?textX+8:textX-8;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.7;ctx.globalAlpha=.92;ctx.beginPath();ctx.moveTo(startX,cy);ctx.lineTo(elbowX,cy);ctx.lineTo(it.tx,it.ty);ctx.stroke();ctx.beginPath();ctx.arc(it.tx,it.ty,3.2,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.textAlign=side==='left'?'right':'left';ctx.textBaseline='top';ctx.fillStyle='#edf5fb';let yy=it.ly+2;for(const ln of it.lines){ctx.fillText(ln,textX,yy);yy+=lineH}}}drawSide(left,'left');drawSide(right,'right');ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.font='500 '+(mobile?16:17)+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';ctx.fillStyle='#7890a5';ctx.fillText(currentView.toUpperCase()+'  |  atlas-supported labels',18,outH-15)}
function syncCrossButton(){const ok=['axial','coronal','sagittal'].includes(currentView),b=$('#labelSection'),h=$('#crossHint');b.disabled=!ok;h.textContent=ok?'Create a textbook-style labeled copy of this exact '+currentView+' slice.':'Switch to axial, coronal, or sagittal view to label the current slice.';if(!ok)$('#crossPanel').hidden=true}
async function labelCrossSection(){if(!['axial','coronal','sagittal'].includes(currentView))return;if(extrasReady)await extrasReady;const src=nv.gl?.canvas||$('#gl'),panel=$('#crossPanel');nv.drawScene();let url='';try{url=src.toDataURL('image/png')}catch(e){console.error(e);$('#crossMeta').textContent='Unable to capture this MRI slice in the current browser.';panel.hidden=false;return}let img;try{img=await loadCrossImage(url)}catch(e){console.error(e);$('#crossMeta').textContent='Unable to reproduce this MRI slice.';panel.hidden=false;return}crossCandidates=collectCrossCandidates();renderTextbookPlate(img,crossCandidates);const mm=nv.frac2mm(nv.scene.crosshairPos).map(v=>Math.round(v*10)/10);$('#crossTitle').textContent=currentView.toUpperCase()+' cross section';$('#crossMeta').textContent='Exact current slice · MNI crosshair '+mm[0]+', '+mm[1]+', '+mm[2]+' mm · '+crossCandidates.length+' atlas-supported labels';panel.hidden=false;requestAnimationFrame(()=>panel.scrollIntoView({behavior:'smooth',block:'nearest'}))}
const nv=new Niivue'''
s = s[:m.start()] + cross_js + s[m.end():]

# The v5 resize handler calls a function that no longer exists. The textbook
# canvas scales responsively in CSS, so no resize redraw is required.
s = s.replace("window.addEventListener('resize',()=>{if(!$('#crossPanel').hidden)renderCrossPins()});", '')

s = s.replace('–','-').replace('—','-')
path.write_text(s)
print('precision v6 patch applied')
