from pathlib import Path
import re, sys

path = Path(sys.argv[1])
s = path.read_text()

# Precision v7 changes only the opt-in cross-section teaching plate.
# The main NeuroAtlas viewer, navigation, FIND, 3D and Anatomy Teacher remain untouched.

old_panel = '<div class="cross-panel" id="crossPanel" hidden><div class="cross-head"><div><div class="ey">TEXTBOOK CROSS SECTION</div><h3 id="crossTitle">Current slice</h3><div class="tiny" id="crossMeta"></div></div><button id="closeCross">CLOSE</button></div><div class="cross-stage textbook" id="crossStage"><canvas id="crossCanvas"></canvas></div><div class="cross-note">Leader lines point to atlas-supported structures sampled from this exact MRI slice. Labels are placed outside the anatomy whenever possible.</div></div>'
new_panel = '<div class="cross-panel" id="crossPanel" hidden><div class="cross-head"><div><div class="ey">HD TEXTBOOK CROSS SECTION</div><h3 id="crossTitle">Current slice</h3><div class="tiny" id="crossMeta"></div></div><div class="cross-actions"><button id="downloadCross" disabled>DOWNLOAD IMAGE</button><button id="closeCross">CLOSE</button></div></div><div class="cross-stage textbook" id="crossStage"><canvas id="crossCanvas"></canvas></div><div class="cross-note">Dense atlas-supported labeling with full structure names. Fine leader lines point to sampled anatomy on this exact MRI slice. Download exports the labeled plate with a small NeuroAtlas watermark.</div></div>'
if old_panel not in s:
    raise SystemExit('v6 cross panel anchor not found')
s = s.replace(old_panel, new_panel, 1)

# Extend only cross-section CSS.
css_old = '.cross-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:8px}.cross-head h3{margin:3px 0 2px;font-size:17px}.cross-stage.textbook{background:#020407;border:1px solid #26384b;border-radius:12px;overflow:hidden}.cross-stage.textbook canvas{display:block;width:100%;height:auto;background:#020407}.cross-note{padding:8px 2px 2px;color:var(--muted);font-size:10px;line-height:1.4}'
css_new = '.cross-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:8px}.cross-head h3{margin:3px 0 2px;font-size:17px}.cross-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.cross-actions button:disabled{opacity:.45}.cross-stage.textbook{background:#020407;border:1px solid #26384b;border-radius:12px;overflow:hidden}.cross-stage.textbook canvas{display:block;width:100%;height:auto;background:#020407}.cross-note{padding:8px 2px 2px;color:var(--muted);font-size:10px;line-height:1.4}'
if css_old not in s:
    raise SystemExit('v6 cross css anchor not found')
s = s.replace(css_old, css_new, 1)

# Mobile cross-section controls remain compact.
s = s.replace('.cross-cta button{width:100%}', '.cross-cta button{width:100%}.cross-actions{width:100%}.cross-actions button{flex:1}', 1)

# Replace the v6 cross-section runtime block with dense, spatially balanced HD labeling.
pat = re.compile(r'function crossKind\(.*?\nconst nv=new Niivue', re.S)
m = pat.search(s)
if not m:
    raise SystemExit('v6 cross runtime block not found')

cross_js = r'''function crossKind(name,src){const x=String(name||'').toLowerCase();if(/ventricle|aqueduct|csf/.test(x))return{kind:'csf',p:170,color:'#67d8ff'};if(src==='JHU'||/internal capsule|external capsule|corona radiata|corpus callosum|corticospinal|cerebellar peduncle|cerebral peduncle|medial lemniscus|cingulum|fornix|fasciculus|thalamic radiation|sagittal stratum|tapetum/.test(x))return{kind:'wm',p:150,color:'#f3c66d'};if(/thalam|caudate|putamen|pallid|hippocamp|amygdala|accumbens|brainstem|midbrain|pons|medulla/.test(x))return{kind:'deep',p:145,color:'#f48bbb'};if(/cerebel|vermis/.test(x))return{kind:'cortex',p:120,color:'#8fe1ad'};return{kind:'cortex',p:90,color:'#8fe1ad'}}
function crossValue(src,frac){const i=vIdx(src),v=nv.volumes?.[i];if(!v||!v.mm2vox||!v.getValue)return 0;const mm=nv.frac2mm(frac),q=v.mm2vox(mm);return Math.round(v.getValue(q[0],q[1],q[2]))||0}
function crossCanonical(name){let x=String(name||'').toLowerCase().replace(/_/g,' ').replace(/\s+/g,' ').trim(),side='';if(/^left\b/.test(x)){side='l';x=x.replace(/^left\s+/,'')}else if(/^right\b/.test(x)){side='r';x=x.replace(/^right\s+/,'')}else if(/, left$/.test(x)){side='l';x=x.replace(/, left$/,'')}else if(/, right$/.test(x)){side='r';x=x.replace(/, right$/,'')}else if(/\sl$/.test(x)){side='l';x=x.replace(/\sl$/,'')}else if(/\sr$/.test(x)){side='r';x=x.replace(/\sr$/,'')}x=x.replace(/\bnucleus\b/g,'').replace(/\bcortex\b/g,'').replace(/\s+/g,' ').trim();return x+'|'+side}
function crossFullName(name){let x=pretty(String(name||'')).replace(/_/g,' ').replace(/\s+/g,' ').trim(),side='';if(/^Left\b/i.test(x)){side='L';x=x.replace(/^Left\s+/i,'')}else if(/^Right\b/i.test(x)){side='R';x=x.replace(/^Right\s+/i,'')}else if(/, left$/i.test(x)){side='L';x=x.replace(/, left$/i,'')}else if(/, right$/i.test(x)){side='R';x=x.replace(/, right$/i,'')}else if(/\sL$/i.test(x)){side='L';x=x.replace(/\sL$/i,'')}else if(/\sR$/i.test(x)){side='R';x=x.replace(/\sR$/i,'')}x=x.replace(/\bCerebelum\b/gi,'Cerebellum').replace(/\bCrus1\b/gi,'Crus I').replace(/\bCrus2\b/gi,'Crus II').replace(/\bFrontal Sup\b/gi,'Superior frontal').replace(/\bFrontal Mid\b/gi,'Middle frontal').replace(/\bFrontal Inf\b/gi,'Inferior frontal').replace(/\bTemporal Sup\b/gi,'Superior temporal').replace(/\bTemporal Mid\b/gi,'Middle temporal').replace(/\bTemporal Inf\b/gi,'Inferior temporal').replace(/\bOccipital Sup\b/gi,'Superior occipital').replace(/\bOccipital Mid\b/gi,'Middle occipital').replace(/\bOccipital Inf\b/gi,'Inferior occipital').replace(/\bParietal Sup\b/gi,'Superior parietal').replace(/\bParietal Inf\b/gi,'Inferior parietal').replace(/\bCingulum Ant\b/gi,'Anterior cingulate').replace(/\bCingulum Mid\b/gi,'Middle cingulate').replace(/\bCingulum Post\b/gi,'Posterior cingulate').replace(/\bParaHippocampal\b/gi,'Parahippocampal');return x+(side?' ('+side+')':'')}
function addCrossBucket(buckets,src,id,name,x,y){if(!id||!name)return;const info=crossKind(name,src),key=crossCanonical(name),rank=(src==='HO'?3:src==='JHU'?2:1);let b=buckets.get(key);if(!b||info.p>b.info.p||(info.p===b.info.p&&rank>b.rank)){b={src,id,name:crossFullName(name),info,rank,pts:[]};buckets.set(key,b)}if(b.src===src&&b.id===id&&b.pts.length<900)b.pts.push([x,y])}
function crossRepresentative(b){let sx=0,sy=0;for(const p of b.pts){sx+=p[0];sy+=p[1]}const mx=sx/b.pts.length,my=sy/b.pts.length;let best=b.pts[0],bd=1e18;for(const p of b.pts){const d=(p[0]-mx)*(p[0]-mx)+(p[1]-my)*(p[1]-my);if(d<bd){bd=d;best=p}}return best}
function spatialPick(list,count,w,h){if(count<=0||!list.length)return[];const selected=[],seen=new Set(),cols=4,rows=4;for(let ry=0;ry<rows&&selected.length<count;ry++)for(let rx=0;rx<cols&&selected.length<count;rx++){const cell=list.filter((c,i)=>!seen.has(i)&&c.x>=rx*w/cols&&c.x<(rx+1)*w/cols&&c.y>=ry*h/rows&&c.y<(ry+1)*h/rows).sort((a,b)=>b.score-a.score);if(cell.length){const c=cell[0],idx=list.indexOf(c);seen.add(idx);selected.push(c)}}for(let i=0;i<list.length&&selected.length<count;i++)if(!seen.has(i)){seen.add(i);selected.push(list[i])}return selected}
function selectCrossCandidates(arr,w,h){const mobile=window.innerWidth<=520,limit=mobile?36:52,cortexGoal=mobile?16:24,nonGoal=limit-cortexGoal,non=arr.filter(c=>c.info.kind!=='cortex'),cortex=arr.filter(c=>c.info.kind==='cortex'),chosen=[],keys=new Set();function add(c){const k=c.src+':'+c.id;if(!keys.has(k)){keys.add(k);chosen.push(c)}}for(const c of spatialPick(non,nonGoal,w,h))add(c);for(const c of spatialPick(cortex,cortexGoal,w,h))add(c);for(const c of spatialPick(arr,limit,w,h)){if(chosen.length>=limit)break;add(c)}return chosen.slice(0,limit)}
function collectCrossCandidates(){const gl=nv.gl?.canvas||$('#gl'),w=gl.width,h=gl.height;if(!w||!h)return[];const buckets=new Map(),step=Math.max(8,Math.round(Math.min(w,h)/72));for(let y=Math.floor(step/2);y<h;y+=step){for(let x=Math.floor(step/2);x<w;x+=step){const f=nv.canvasPos2frac([x,y]);if(!f||f[0]<0)continue;if(hoReady){const id=crossValue('HO',f),nm=HO_LABELS[id];if(id>0&&nm)addCrossBucket(buckets,'HO',id,nm,x,y)}if(jhuReady){const id=crossValue('JHU',f),nm=JHU_LABELS[id];if(id>0&&nm)addCrossBucket(buckets,'JHU',id,pretty(nm),x,y)}const a=crossValue('AAL',f),an=labels[a];if(a>0&&an)addCrossBucket(buckets,'AAL',a,pretty(an),x,y)}}const arr=[];for(const b of buckets.values()){if(!b.pts.length)continue;const best=crossRepresentative(b),count=b.pts.length;arr.push({...b,x:best[0],y:best[1],count,score:b.info.p*100000+Math.min(count,9999)})}arr.sort((a,b)=>b.score-a.score);return selectCrossCandidates(arr,w,h)}
function wrapCrossText(ctx,text,maxWidth){const words=String(text).split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxWidth||!line)line=test;else{lines.push(line);line=word}}if(line)lines.push(line);return lines}
function distributeCrossLabels(items,minY,maxY,gap){items.sort((a,b)=>a.ty-b.ty);let cursor=minY;for(const it of items){it.ly=Math.max(it.ty-it.h/2,cursor);cursor=it.ly+it.h+gap}if(items.length){let overflow=(items[items.length-1].ly+items[items.length-1].h)-maxY;if(overflow>0){for(let i=items.length-1;i>=0;i--){items[i].ly-=overflow;if(i>0){const allowed=items[i].ly-gap-items[i-1].h;if(items[i-1].ly>allowed)overflow=items[i-1].ly-allowed;else overflow=0}}}if(items[0].ly<minY){const d=minY-items[0].ly;for(const it of items)it.ly+=d}}}
function loadCrossImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url})}
function drawCrossWatermark(ctx,w,h){const box=58,x=w-box-26,y=h-box-24;ctx.save();ctx.globalAlpha=.62;ctx.fillStyle='#07111a';ctx.strokeStyle='#72d9ff';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x,y,box,box,15);ctx.fill();ctx.stroke();ctx.strokeStyle='#9ce8ff';ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(x+14,y+42);ctx.lineTo(x+14,y+16);ctx.lineTo(x+32,y+42);ctx.lineTo(x+32,y+16);ctx.stroke();ctx.globalAlpha=.72;ctx.textAlign='right';ctx.fillStyle='#d9e9f6';ctx.font='600 18px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';ctx.fillText('NeuroAtlas MRI',x-12,y+25);ctx.fillStyle='#91a8bb';ctx.font='500 13px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';ctx.fillText('Dr. Shashank Neupane and Team',x-12,y+46);ctx.restore()}
function renderTextbookPlate(img,candidates){const dst=$('#crossCanvas'),src=nv.gl?.canvas||$('#gl'),mobile=window.innerWidth<=520,outW=mobile?1600:2200,imgW=mobile?900:1260,font=mobile?40:46,lineH=font+9,side=(outW-imgW)/2,maxText=Math.max(260,side-92),scale=imgW/src.width,imgH=Math.round(src.height*scale);dst.width=outW;dst.height=1200;let ctx=dst.getContext('2d');ctx.font='600 '+font+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';const pre=candidates.map(c=>{const lines=wrapCrossText(ctx,c.name,maxText),h=lines.length*lineH+8;return{...c,lines,h}});const leftPre=[],rightPre=[];for(const p of pre){if(Math.abs(p.x-src.width/2)<src.width*.06){(leftPre.length<=rightPre.length?leftPre:rightPre).push(p)}else(p.x<src.width/2?leftPre:rightPre).push(p)}const gap=mobile?11:13,sideHeight=a=>a.reduce((n,it)=>n+it.h,0)+Math.max(0,a.length-1)*gap,outH=Math.max(mobile?1280:1500,imgH+150,sideHeight(leftPre)+110,sideHeight(rightPre)+110),imgX=Math.round((outW-imgW)/2),imgY=Math.round((outH-imgH)/2);dst.height=outH;ctx=dst.getContext('2d');ctx.fillStyle='#020407';ctx.fillRect(0,0,outW,outH);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,imgX,imgY,imgW,imgH);ctx.save();ctx.strokeStyle='rgba(135,157,180,.4)';ctx.lineWidth=2;ctx.strokeRect(imgX+1,imgY+1,imgW-2,imgH-2);ctx.restore();ctx.font='600 '+font+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';const mapItem=p=>({...p,tx:imgX+p.x/src.width*imgW,ty:imgY+p.y/src.height*imgH});const left=leftPre.map(mapItem),right=rightPre.map(mapItem),y0=36,y1=outH-92;distributeCrossLabels(left,y0,y1,gap);distributeCrossLabels(right,y0,y1,gap);function drawSide(items,sideName){for(const it of items){const cy=it.ly+it.h/2,color=it.info.color,textX=sideName==='left'?imgX-42:imgX+imgW+42,elbowX=sideName==='left'?imgX-15:imgX+imgW+15,startX=sideName==='left'?textX+10:textX-10;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2.5;ctx.globalAlpha=.93;ctx.beginPath();ctx.moveTo(startX,cy);ctx.lineTo(elbowX,cy);ctx.lineTo(it.tx,it.ty);ctx.stroke();ctx.beginPath();ctx.arc(it.tx,it.ty,4.5,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.textAlign=sideName==='left'?'right':'left';ctx.textBaseline='top';ctx.fillStyle='#f0f6fb';let yy=it.ly+3;for(const ln of it.lines){ctx.fillText(ln,textX,yy);yy+=lineH}}}drawSide(left,'left');drawSide(right,'right');const mm=nv.frac2mm(nv.scene.crosshairPos).map(v=>Math.round(v*10)/10);ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.font='600 '+(mobile?24:27)+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';ctx.fillStyle='#a9bdce';ctx.fillText(currentView.toUpperCase()+' CROSS SECTION',24,34);ctx.font='500 '+(mobile?20:22)+'px -apple-system,BlinkMacSystemFont,"SF Pro Display",Arial,sans-serif';ctx.fillStyle='#71899e';ctx.fillText('MNI '+mm[0]+', '+mm[1]+', '+mm[2]+' mm  |  '+candidates.length+' atlas-supported labels',24,outH-26);drawCrossWatermark(ctx,outW,outH)}
function syncCrossButton(){const ok=['axial','coronal','sagittal'].includes(currentView),b=$('#labelSection'),h=$('#crossHint');b.disabled=!ok;h.textContent=ok?'Create a dense HD textbook-style labeled copy of this exact '+currentView+' slice.':'Switch to axial, coronal, or sagittal view to label the current slice.';if(!ok){$('#crossPanel').hidden=true;const d=$('#downloadCross');if(d)d.disabled=true}}
async function labelCrossSection(){if(!['axial','coronal','sagittal'].includes(currentView))return;if(extrasReady)await extrasReady;const src=nv.gl?.canvas||$('#gl'),panel=$('#crossPanel'),down=$('#downloadCross');if(down)down.disabled=true;nv.drawScene();let url='';try{url=src.toDataURL('image/png')}catch(e){console.error(e);$('#crossMeta').textContent='Unable to capture this MRI slice in the current browser.';panel.hidden=false;return}let img;try{img=await loadCrossImage(url)}catch(e){console.error(e);$('#crossMeta').textContent='Unable to reproduce this MRI slice.';panel.hidden=false;return}crossCandidates=collectCrossCandidates();renderTextbookPlate(img,crossCandidates);const mm=nv.frac2mm(nv.scene.crosshairPos).map(v=>Math.round(v*10)/10);$('#crossTitle').textContent=currentView.toUpperCase()+' cross section';$('#crossMeta').textContent='Exact current slice · MNI crosshair '+mm[0]+', '+mm[1]+', '+mm[2]+' mm · '+crossCandidates.length+' atlas-supported labels · HD export ready';if(down)down.disabled=false;panel.hidden=false;requestAnimationFrame(()=>panel.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function downloadCrossSection(){const c=$('#crossCanvas');if(!c||!c.width||!c.height)return;const mm=nv.frac2mm(nv.scene.crosshairPos).map(v=>Math.round(v));const name='NeuroAtlas_'+currentView+'_'+mm.join('_')+'.png';const save=url=>{const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()};if(c.toBlob)c.toBlob(blob=>{if(!blob)return save(c.toDataURL('image/png'));const url=URL.createObjectURL(blob);save(url);setTimeout(()=>URL.revokeObjectURL(url),1500)},'image/png',1);else save(c.toDataURL('image/png'))}
const nv=new Niivue'''
s = s[:m.start()] + cross_js + s[m.end():]

# Add download event without touching main viewer behavior.
event_old = "$('#outline').onchange=e=>nv.setAtlasOutline(+e.target.value);$('#labelSection').onclick=labelCrossSection;$('#closeCross').onclick=()=>{$('#crossPanel').hidden=true};syncCrossButton();"
event_new = "$('#outline').onchange=e=>nv.setAtlasOutline(+e.target.value);$('#labelSection').onclick=labelCrossSection;$('#downloadCross').onclick=downloadCrossSection;$('#closeCross').onclick=()=>{$('#crossPanel').hidden=true};syncCrossButton();"
if event_old not in s:
    raise SystemExit('cross event anchor not found')
s = s.replace(event_old, event_new, 1)

s = s.replace('–','-').replace('—','-')
path.write_text(s)
print('precision v7 patch applied')
